/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import javax.swing.JCheckBoxMenuItem;
import javax.swing.JDesktopPane;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;

/**
 *
 * @author pc
 */
public class view_registro extends javax.swing.JFrame {

    /**
     * Creates new form view_registro
     */
    public view_registro() {
        initComponents();
    }

    public JMenuItem getJMenuCrearProducto() {
        return JMenuCrearProducto;
    }

    public void setJMenuCrearProducto(JMenuItem JMenuCrearProducto) {
        this.JMenuCrearProducto = JMenuCrearProducto;
    }

    public JMenuItem getJMenuCrearUsuario() {
        return JMenuCrearUsuario;
    }

    public void setJMenuCrearUsuario(JMenuItem JMenuCrearUsuario) {
        this.JMenuCrearUsuario = JMenuCrearUsuario;
    }

    

    public JMenuItem getjCrearPersona1() {
        return jCrearPersona1;
    }

    public void setjCrearPersona1(JMenuItem jCrearPersona1) {
        this.jCrearPersona1 = jCrearPersona1;
    }

    public JDesktopPane getEscritorio() {
        return escritorio;
    }

    public void setEscritorio(JDesktopPane escritorio) {
        this.escritorio = escritorio;
    }

    

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        jCrearUsuario = new javax.swing.JMenu();
        jCrearPersona1 = new javax.swing.JMenuItem();
        JMenuCrearProducto = new javax.swing.JMenuItem();
        JMenuCrearUsuario = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        escritorio.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 259, Short.MAX_VALUE)
        );

        jMenuBar2.setBackground(new java.awt.Color(51, 51, 255));

        jCrearUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/image/btnconfig.png"))); // NOI18N

        jCrearPersona1.setText("Persona");
        jCrearPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCrearPersona1ActionPerformed(evt);
            }
        });
        jCrearUsuario.add(jCrearPersona1);

        JMenuCrearProducto.setText("Producto");
        jCrearUsuario.add(JMenuCrearProducto);

        JMenuCrearUsuario.setText("Usuario");
        jCrearUsuario.add(JMenuCrearUsuario);

        jMenuBar2.add(jCrearUsuario);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vista/image/btnReportes.png"))); // NOI18N
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCrearPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCrearPersona1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCrearPersona1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem JMenuCrearProducto;
    private javax.swing.JMenuItem JMenuCrearUsuario;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jCrearPersona1;
    private javax.swing.JMenu jCrearUsuario;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
